# Generated by Django 3.2.6 on 2021-08-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='file',
        ),
        migrations.CreateModel(
            name='AlbumImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='album/images')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albumapp.album')),
            ],
        ),
    ]
