# Generated by Django 3.2.6 on 2021-08-31 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0002_auto_20210828_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimages',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='albumapp.album'),
        ),
    ]
