# Generated by Django 3.2.6 on 2021-09-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0009_alter_albumimages_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimages',
            name='media',
            field=models.CharField(max_length=30),
        ),
    ]
