# Generated by Django 3.2.6 on 2021-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0014_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
